# Generated by Django 5.0.2 on 2024-02-23 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "furnituretype",
                    models.CharField(
                        choices=[("chair", "Chaise1"), ("table", "Table1")],
                        max_length=50,
                    ),
                ),
                (
                    "chairbacktype",
                    models.CharField(
                        choices=[("flat", "Flat Back"), ("rods", "With Rods")],
                        max_length=50,
                    ),
                ),
                (
                    "thickness_backchair",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "nbrods",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("length", models.FloatField(default=0)),
                ("width", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("height3", models.FloatField(default=0)),
            ],
        ),
    ]
