# Generated by Django 5.0.2 on 2024-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('hauteur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('profondeur', models.FloatField()),
                ('style', models.CharField(max_length=100)),
            ],
        ),
    ]
