# Generated by Django 5.0.2 on 2024-02-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FurnitureConfigurator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="furniture",
            old_name="height3",
            new_name="height2",
        ),
    ]
