# Generated by Django 5.0.2 on 2024-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureConfigurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('style', models.CharField(choices=[(1, 'Type 1'), (2, 'Type 2')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Meuble',
        ),
    ]
