# Generated by Django 5.0.2 on 2024-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureConfigurator', '0002_table_delete_meuble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('style', models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='style',
            field=models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2')], max_length=100),
        ),
    ]
