# Generated by Django 5.0.2 on 2024-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FurnitureConfigurator", "0003_remove_furniture_height2"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="height2",
            field=models.FloatField(default=0),
        ),
    ]
