# Generated by Django 5.0.2 on 2024-02-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FurnitureConfigurator", "0004_furniture_height2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="furniture",
            name="height2",
        ),
    ]
